# Generated by Django 3.0.5 on 2020-05-09 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoajax', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['completed', 'timestamp']},
        ),
    ]
